[tool.poetry]
name = "enviro"
version = "0.1.0"
description = ""
authors = ["mgx <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
envirophat = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
